### PR TITLE
Add support for Raw IPMI Commands

### PR DESCRIPTION
**Pull request by mdhorn**
In using your package I needed to use raw commands, and thought others might want this functionality as well.

### CODE REVIEW

**Comment by mdhorn** [comment]
@bougou This is really useful for OEM commands. Let me know if you have questions or concerns.

**Comment by bougou** [comment]
@mdhorn There may be a typo error in the code, can you confirm it?

**Comment by mdhorn** [comment]
> @mdhorn There may be a typo error in the code, can you confirm it?

@bougou Where do you believe there is a typo?  I'm building and using the code now. 
I'm happy to update or correct if you tell me the concern.

**Comment by bougou** [comment]
@mdhorn 
image

I think you mean to fill `out` at offset 0. You can check the returned err.

```go
_, err := packBytes(req.Data, out, 0)
```

**Comment by mdhorn** [comment]
> @mdhorn image
> 
> I think you mean to fill `out` at offset 0. You can check the returned err.
> 
> ```go
> _, err := packBytes(req.Data, out, 0)
> ```

@bougou Oh, good catch. 
I fixed the offset and tested it.
I could check for an error, but the Request interface does not currently account for error handling. 
Thanks!

**Comment by mdhorn** [comment]
@bougou Thanks for the merge. Are you planning a new release in the near future? If not, I'll just plan to use the latest for now.

**Pull request merged**
